# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginApp
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire'
  pod "SwiftSpinner"
  pod "PromiseKit", "~> 6.8"
  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'KeychainSwift'

end
